### PR TITLE
Implement resize callback for all charts

### PR DESCRIPTION
**Pull request by johnSamilin**
fixes https://github.com/OHDSI/Atlas/issues/1105

### CODE REVIEW

**Comment by chrisknoll** [comment]
@johnSamilin, this resize callback was to completely redraw the component so that the font sizes get rendered properly, and also the 'inset' of the legend can be applied differently based on the relative size of the legend and the overall graph size.

Just relying on the 'viewbox' property causes the text to get shrunk.

The isse described in OHDSIAtlas#1105 I believe comes from the incorrect width/height dimensions being fed into the control. Somehow it's sending in values that are larger than the actual component space and it causes that slight growth between renders.

**Comment by chrisknoll** [comment]
Here is the behavior of the current master branch:
Small:
image

Resized larger such that legend appears (inset):
image

Resized large enough to allow legend to appear outside the plot:
image

You'll have to open the above images in order to see 'actual size' but notice that between resizes that the font size remains consistent no matter how the plot is sized.

Now, with your PR, same resize steps:

Starting with default window size large (notice the legend is inset, and does not change):
image

Medium, fonts get smaller almost unreadable:
image

Small now, text is unreadable, the legened did not hide:
image

**Comment by johnSamilin** [comment]
@chrisknoll then why only line chart has this callback? what about the donut chart or any other? all of them have axis labels, and donut also has a legend

**Comment by chrisknoll** [comment]
True! This was just a focused fix to address some rendering issues related to line plot, but this could be hoisted up to the base 'chart' level and applied to all plots.

**Comment by chrisknoll** [comment]
I've tried it both ways, having the chart redraw itself has had the best result.

**Comment by chrisknoll** [comment]
Ok, if you think it's possible to have the same fidelity using those techniques, that would be great to see.

Still wondering how you can adjust ticks and orient axis labels based on dimensions via css and media queries, but I'm always willing to learn something new.

**Comment by chrisknoll** [comment]
Question:
couldn't we add the debounce implementation to the utils module of the library instead of making a new dependency on a 500k lodash library?  the debounce is only 12 lines of code, is that worth making a dependency on a 500k size library?

**Comment by johnSamilin** [comment]
It gives us only 50 k of size

**Comment by chrisknoll** [comment]
Apolgoies! you are corect, this cdn shows just 23k download size. I forget where I saw a large bundle size on one of the other libs on atlas. But for this PR, the dependnecy on lodash isn't a large burdeon. Thanks. let me check the local tests for this change and let you know if there's any problems.

**Comment by chrisknoll** [comment]
@johnSamilin , sorry to distract this PR but i found where i saw lodash being so large:

image

This is the file that's downloaded with atlas. the difference is it is comming from a NPM install vs a CDN.  Do you know if it is possible to get a smaller lodash lib from NPM that can be used in Atlas?

**Comment by chrisknoll** [comment]
@johnSamilin : i took the liberty of applying the resize logic across the different chart types (by hoisting the resize logic to the base chart class, and having subclasses call super()).  A nice use of the class hierarchy!  I need to import this component into my local atlas env to ensure nothing breaks, but I wanted to share these changes with you first.

**Comment by johnSamilin** [comment]
>Do you know if it is possible to get a smaller lodash lib from NPM that can be used in Atlas?
In theory, it could be achieved by removing `lodash` dependency and introducing a number of atomic dependencies like `lodash.flatten`, `lodash.find` etc. I will check

**Comment by johnSamilin** [comment]
@chrisknoll it won't be effective because of two main reasons:
1. `ohdsi.util.js` uses almost all the lodash's functionality, so it will be loaded anyway
2. npm doesn't have all the modularized packages from lodash. for example, `lodash.differenceWith` and a bunch of others don't exist

**Pull request merged**
