### PR TITLE
Moved Atlas charts into a separate module

### PR DESCRIPTION
**Pull request by pavgra**
For [the pull-request](https://github.com/OHDSI/Atlas/pull/417)

### CODE REVIEW

**Comment by chrisknoll** [comment]
Hi, @pavgra ,
  I really do appreciate the work you put into refactoring out the one library into several sub modules, it really cleans up the code. Also I like using the more modernized syntax for the module declarations.  Looks like it's probably worth the overhead of the transpile step (which will be transparent to anyone just importing the module).

Would you please revert the API change where instead of calling the static method 'render()' on each component, instead the API returns a constructor function for each of the chart types.  This will allow us to just drop in the shared component into other places that use this charting API, I understand your point that the components are stateless at the moment, but the plan was that there would be state maintained at a future point in the evolution of the code, and making these static calls to render is a step backwards from that goal.

**Comment by chrisknoll** [comment]
I'm attempting to get this branch working locally. After installing node (latest release) and doing npm install, I am giving the following warnings:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}                 )
npm WARN Visualizations@1.0.0 requires a peer of numeral@^2.0.6 but none was installed.
npm WARN Visualizations@1.0.0 No license field.
```

Also, looking at the install tree for d3-tip, looks like it's pulling down a version of d3 @v4.9.1 which references d3-shape@1.1.1 but the main module references d3-shape@1.2.0.  I get the different dependencies have different nested dependencies and so each individual version of the referenced libraries will be brought in (and tree-shaking will remove anything unused) but I'm wondering if it's possible to get a set of dependencies that work off of the same version of the dependencies.

**Comment by pavgra** [comment]
@chrisknoll, we are going to update the pull-request with bringing back an original API, and will double check all the dependencies. This is going to happen this or next week. But with current state we tested everything built together and it worked

**Comment by chrisknoll** [comment]
Thanks, i'm trying to work on getting this running locally. How'd you test this?  I don't see any test html files in the repo that you could launch into and step through code.  Was it a matter of changing the AchillesWeb or Atlas requirejs.config to point to the location that the webpack build emit the build?

I reviewed the code you added and it looks like some things were striped out of the module, specifically the resizing of the SVG:
```
$(window).on("resize", {
		container: $(target),
		chart: $(target + " svg"),
		aspect: w / h
	},
	function (event) {
		var targetWidth = event.data.container.width();
		event.data.chart.attr("width", targetWidth);
		event.data.chart.attr("height", Math.round(targetWidth / event.data.aspect));
	}).trigger("resize");
```

I also don't see how jquery is being imported for use (and alised over to $).  If the above was just a matter of getting it working by removing code, could you also point out where other removals were made?

I'm thinking about creating an alternative branch where this module is just simply a es5 module definition that doesn't require transpiling or special build tools to start developing.  I know you made some comments about overcomplication of the code, and I think (based on what i've had to do so far to just get it built) this is way more complicated then the current process which is just save changes and reload browser (and what you see in the browser is the code you wrote).  The simplest approach would be just to drop the chart.js file directly into the root of the repo and point package.json to it.  

A better approach would be to follow that you've done here which is split the module into sub-modules for each chart. I don't think I'd be using es6 module syntax due to the need for transpiling, but otherwise most of the code would follow the structure of a main module entry that references the submodules and exposes them.  So I'll be working through that in the meantime.  

The priority for me is that I'd like to continue maintaining the chart library (as I'm the primary author of the original library) and so what's important to me is being able to support it and quickly debug.  Maybe you could help me along with getting familiar with this new environment you're proposing.  It would be helpful if there was a getting started section in the Readme.md file that described what it takes to start working.

**Comment by chrisknoll** [comment]
@pavgra ,
 I'd like to try to collaborate with you about transitioning the embedded charting module in Atlas as the standalone library that we're trying to get to with this PR.  I think that what you've put together here may very well be the final target that we arrive at, but as I'm primary maintainer of the code, it's not clear how the code has been changed to appear in this final form.  To that end, I've started up a new branch [here](/ohdsi/visualizations/tree/chartlib-part1).

This first draft simply moves the code as a UMD module into this repository, and sets up some examples (and adds to the Readme.md file to give some instructions).  From here, I'm thinking of making a second branch to show how it'd be split up in to the individual files and developed under the requirejs module loader.  After the files are split, then I think we can see a clearer path to go from the code as it exists today into a form that you are proposing in this PR.

I'm not sure where the best forum is to collaborate on this:  talk about it attached to this PR or create a forum thread on ohdsi.org so that it's not attached to any specific github location.  Let me know what your thoughts are.

**Comment by pavgra** [comment]
@chrisknoll, we removed static methods and updated original Atlas PR.

> I reviewed the code you added and it looks like some things were striped out of the module, specifically the resizing of the SVG:
As I remember, we nothing removed out. That original block of code was for preserving aspect ratio of graph, using explicit listeners and manual handling. Now it is done via native SVG attribute, without need to do extra coding and computing:
`
.attr('preserveAspectRatio', 'xMinYMin meet')
`

> I also don't see how jquery is being imported for use (and alised over to $). If the above was just a matter of getting it working by removing code, could you also point out where other removals were made?
For what reason jQuery is required here? We removed it as it brings no value but adds a lot to the bundle size.

> How'd you test this?
Deployed the Atlas which we suggest via pull-request and tested everything manually.

> Let me know what your thoughts are.
Currently, I feel that discussions are going to take much more time that development did.

Have I missed any of your questions?

**Pull request closed without merging**
