### PR TITLE
Fixed scatterplot long labels

### PR DESCRIPTION
**Pull request by vlbe**
Fixes https://github.com/OHDSI/Atlas/issues/1758

### CODE REVIEW

**Comment by chrisknoll** [comment]
Why not use the 'wrap' function?  It will make a single line element into a multi line, which you then can rotate, get the actual width and then offset the left margin based on the width of the element (which, the offeset is actually already happening in the code, because it calculates the offset from the width of the Y-axis label based on font-size).

That way, you don't have to truncate the text.

**Comment by vlbe** [comment]
@chrisknoll I thougt about 'wrap' but decided to go with 'truncate' because it's possible that labels would be really long and they can be divided in 4-5 lines of text => so the actual width/height of the graph will be very small. I added title so you can hover over truncated label to see full text.

**Comment by pavgra** [comment]
@chrisknoll , would be great if we could merge it which would allow us to resolve several issues for Atlas 2.7.2. Are there any non-satisfied comments now?

**Comment by chrisknoll** [comment]
Tested this. The truncation and hover of label works.  Before closing this out, I'd like to again consider applying some level of word-wrapping to this in addition to truncation.  I agree that only applying wrapping could lead to multiple lines of labels, which we would not want.  However, allowing 1 level of wrapping would let you see most cases the complete label.

The reason why I'm pushing back on this is:  the tooltips work fine to handle long text in a browser setting. However, people like to grab images of graphs and use them in research.  A tooltip doesn't work in the printed setting.  Therefore, if we allowed wrapping up to 2 lines, truncated everything else, we'd handle more cases of long labels.

If there's no more time to work on this, we can go with the PR as-is and I can open a separate issue to revisit allowing 'up to 2 levels of wrapping on long labels'.  If you guys think it's worth pursuing in this PR. then we can wait.  Let me know which way you want to go.

**Comment by chrisknoll** [comment]
Ok, per our conference call, we'll close this with the current implementation merged in, and open a separate issue to make it more 'print friendly'.

**Pull request merged**
